# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3.8"
services:
  labs-automation:
    build:
      context: ../
      dockerfile: ./infrastructure/Dockerfile
    volumes: 
      - ../:/src
      - ./m2:/root/.m2 #caching of MVN packages
  selenium-hub:
    image: selenium/hub:4.0.0-alpha-7-prerelease-20201009
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.0.0-alpha-7-prerelease-20201009
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443      
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - VNC_NO_PASSWORD=1 # Used along with node-chrome-debug. It won't require password for VNC.
  # firefox:
  #   image: selenium/node-firefox:3.141.59-vanadium
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444